name: Build and push Docker Image

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image and push to murali94k docker repo
      run: |
        sha=${{ github.sha }}
        echo ${sha:0:8}
        echo "${{secrets.DOCKER_HUB_PASSWORD}}" | docker login -u "murali94k" --password-stdin
        docker build -t murali94k/node_app:${sha:0:8} .
        docker push murali94k/node_app:${sha:0:8}
