name: Build and push Docker Image

on:
  push:
    branches: [ "master", "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image and push to murali94k docker repo
      run: |
        echo "${{secrets.DOCKER_HUB_PASSWORD}}" | docker login -u "murali94k" --password-stdin
        docker build -t murali94k/node_app:v1.0 .
        docker push murali94k/node_app:v1.0
